files:
  include: '**/*.scss'
  ignore:
      - 'node_modules/**/*.scss'
      - 'design/styleguide/**/*.scss'
      - 'design/sass/dependencies/**/*.scss'
      - 'design/preview/dependencies/**.scss'
      - 'design/node_modules/**/*.scss'
      - 'react-apps/**/*.scss'
      - 'webapp/node_modules/**/*.scss'
options:
  formatter: stylish
  max-warnings: 999999999
  merge-default-rules: false
rules:
  bem-depth: 0
  border-zero:
    - 2
    - convention: zero
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format: 0
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format: 0
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format: 0
  indentation:
    - 0
    # Disabled because it messes with pretty indentation
  leading-zero:
    - 2
    - include: true
  mixin-name-format: 0
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 5
  no-color-keywords: 1
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties:
      - 0
      # sass-lint doesn't support fallbacks, wtf
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors:
    - 2
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-transition-all: 0
  no-url-protocols: 0
  no-vendor-prefixes:
    - 1
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 1
  placeholder-name-format: 0
  property-sort-order:
    - 2
    - ignore-custom-properties: false
  property-units:
    - 2
    - global:
        - em
        - rem
        - px
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - rad
        - ms
        - s
        - '%'
      per-property:
        font-size:
          - em
          - rem
          - '%'
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
        - 1
        - 2
        - 3
        - 4
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma:
    - 2
    - include: true
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property:
    - 0
    - properties: []
  variable-name-format: 0
  zero-unit: 2
